name: HealthSync CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      api-gateway:
        description: '🚪 API Gateway'
        type: boolean
        default: false
      frontend:
        description: '🌐 Frontend'
        type: boolean
        default: false
      doctor-service:
        description: '🩺 Doctor Service'
        type: boolean
        default: false
      appointment-service:
        description: '📅 Appointment Service'
        type: boolean
        default: false
      patient-service:
        description: '🧑‍⚕️ Patient Service'
        type: boolean
        default: false
      prescription-service:
        description: '💊 Prescription Service'
        type: boolean
        default: false
      payment-service:
        description: '💳 Payment Service'
        type: boolean
        default: false
      notification-service:
        description: '🔔 Notification Service'
        type: boolean
        default: false
      deploy-all:
        description: '🚀 Deploy ALL services'
        type: boolean
        default: false

jobs:

  sonar-api-gateway:
    if: ${{ github.event.inputs.api-gateway == 'true' || github.event.inputs.deploy-all == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: cd services/api-gateway && npm install
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: services/api-gateway
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sonar-frontend:
    if: ${{ github.event.inputs.frontend == 'true' || github.event.inputs.deploy-all == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: frontend/
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sonar-doctor-service:
    if: ${{ github.event.inputs.doctor-service == 'true' || github.event.inputs.deploy-all == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: cd services/doctor-service && npm install
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: services/doctor-service
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sonar-appointment-service:
    if: ${{ github.event.inputs.appointment-service == 'true' || github.event.inputs.deploy-all == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: cd services/appointment-service && npm install
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: services/appointment-service
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sonar-patient-service:
    if: ${{ github.event.inputs.patient-service == 'true' || github.event.inputs.deploy-all == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: cd services/patient-service && npm install
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: services/patient-service
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sonar-prescription-service:
    if: ${{ github.event.inputs.prescription-service == 'true' || github.event.inputs.deploy-all == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: cd services/prescription-service && npm install
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: services/prescription-service
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sonar-payment-service:
    if: ${{ github.event.inputs.payment-service == 'true' || github.event.inputs.deploy-all == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: cd services/payment-service && npm install
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: services/payment-service
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sonar-notification-service:
    if: ${{ github.event.inputs.notification-service == 'true' || github.event.inputs.deploy-all == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd services/notification-service
          pip install -r requirements.txt
          python -m py_compile src/main.py
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: services/notification-service
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}